apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::608539128050:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::608539128050:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1QTPUR9L75L0T
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2021-11-30T19:17:47Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1352"
  uid: 1d59b240-e40d-4f99-934d-ca8cea28ac4f
